system::site.name:
    type: string
    default:
        - .png
        - .jpg
        - .jpeg
        - .gif
        - .bmp
    description:
system::settings.image:
    type: string
    default:
        - .png
        - .jpg
        - .jpeg
        - .gif
        - .bmp
    description:
system::settings.engine:
    type: string
    default: gd
system::settings.video:
    type: integer
    default: 2048