# key specification is "namespace::group.key"
system::site.name :
    # type default is string, can not setting by default.
    type : string
    default : 罂粟网络
    description : 网站名称
system::site.is_open :
    type : int
    default : 1
    description : 是否开启
system::site.close_reason :
    description : 站点关闭原因
system::site.copyright :
    description : 版权说明
