<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrderTotalStatisticsTable extends Migration
{
	/**
	 * Run the migrations.
	 * @return void
	 */
	public function up()
	{
		Schema::create('order_total_statistics', function (Blueprint $table) {
			$table->increments('id')->comment('ID');
			$table->integer('hunter_earn')->nullable()->comment('累计赚取');
			$table->integer('hunter_handle_num')->nullable()->comment('累计接单数量');
			$table->integer('hunter_win_num')->nullable()->comment('累计胜场');
			$table->decimal('hunter_win_rate', 10, 2)->nullable()->comment('累计胜率');
			$table->integer('girl_hunter_hour')->nullable()->comment('女猎手累计服务时长');
			$table->integer('boss_create_num')->nullable()->comment('下单数');
			$table->integer('boss_win_num')->nullable()->comment('下单胜场数');
			$table->decimal('boss_win_rate', 10, 2)->nullable()->comment('下单胜率');
		});
	}

	/**
	 * Reverse the migrations.
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('order_total_statistics');
	}
}
