<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateGamePriceTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('game_price', function (Blueprint $table) {
            $table->increments('id');
            $table->string('dan', 20)->comment('段位名称');
            $table->decimal('hunter_display', 8, 2)->default(0.00)->comment('普通猎手显示价格');
            $table->decimal('hunter_discount', 8, 2)->default(0.00)->comment('普通猎手折扣价格');
            $table->decimal('hunter_final', 8, 2)->default(0.00)->comment('普通猎手最终价格');
            $table->decimal('good_hunter_display', 8, 2)->default(0.00)->comment('优质猎手显示价格');
            $table->decimal('good_hunter_discount', 8, 2)->default(0.00)->comment('优质猎手折扣价格');
            $table->decimal('good_hunter_final', 8, 2)->default(0.00)->comment('优质猎手最终价格');
            $table->decimal('golden_hunter_display', 8, 2)->default(0.00)->comment('金牌猎手显示价格');
            $table->decimal('golden_hunter_discount', 8, 2)->default(0.00)->comment('金牌猎手折扣价格');
            $table->decimal('golden_hunter_final', 8, 2)->default(0.00)->comment('金牌猎手实际价格');
            $table->unsignedTinyInteger('game')->comment('所属游戏');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            $table->unique('id', 'id_UNIQUE');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('game_price');
    }
}
