<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrderCouponTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('order_coupon', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title', 100)->comment('优惠券名称');
            $table->string('type', 45)->comment('优惠券类型(免单,满减)');
            $table->unsignedInteger('account_id')->comment('满减抵扣');
            $table->unsignedInteger('game_id')->comment('适用游戏');
            $table->string('district', 45)->comment('限制');
            $table->decimal('amount', 10, 2)->default(0.00)->comment('满减金额');
            $table->decimal('discount', 10, 2)->default(0.00)->comment('满减抵扣');
            $table->string('status', 45)->comment('是否启用（expired : 已过期、unused 未使用、used 已使用）');
            $table->dateTime('gained_at')->nullable()->comment('获取时间');
            $table->dateTime('started_at')->nullable()->comment('开始时间');
            $table->dateTime('ended_at')->nullable()->comment('结束时间');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('order_coupon');
    }
}
