<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrderCommentTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('order_comment', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('account_id')->comment('评价人id');
            $table->unsignedInteger('to_account_id')->comment('猎手id');
            $table->string('order_no', 50)->comment('订单号');
            $table->unsignedTinyInteger('order_type')->comment('订单类型↵0:普通订单 1：陪玩订单 2：车队订单');
            $table->unsignedTinyInteger('star')->comment('评价星级↵1-5分(1-5星)');
            $table->string('content', 255)->comment('评价内容');
            $table->dateTime('comment_at')->nullable()->comment('评价日期');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('order_comment');
    }
}
