<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateOrderRangeStatisticsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('order_range_statistics', function (Blueprint $table) {
            $table->increments('id')->comment('用户id');
            $table->string('type', 45)->nullable()->comment('year(2017),day(2017-08-01),week(2017-23),month(2017-12)');
            $table->string('range', 45)->nullable()->comment('范围');
            $table->string('hunter_earn', 45)->nullable()->comment('赚取');
            $table->string('hunter_handle_num', 45)->nullable()->comment('接单数');
            $table->decimal('hunter_win_rate', 10, 2)->nullable()->comment('胜率');
            $table->string('hunter_win_num', 45)->nullable()->comment('胜场数');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('order_range_statistics');
    }
}
