<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSiteTagTable extends Migration
{
	/**
	 * Run the migrations.
	 * @return void
	 */
	public function up()
	{
		Schema::create('site_tag', function (Blueprint $table) {
			$table->increments('id');
			$table->string('title', 255)->default('')->comment('标题');
			$table->string('spell', 100)->default('')->comment('拼写');
			$table->string('first_letter', 20)->default('')->comment('首拼');
			$table->integer('list_order')->default(0)->comment('排序');
			$table->integer('ref_num')->default(0)->comment('关联数量');
			$table->dateTime('created_at')->nullable();
			$table->dateTime('updated_at')->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('site_tag');
	}
}
