<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateArticleContentTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('article_content', function(Blueprint $table) {
			$table->increments('id');
			$table->integer('parent_id');
			$table->integer('book_id')->comment('所属文档ID');
			$table->string('title', 255);
			$table->string('description', 255);
			$table->text('content_md');
			$table->string('author', 50);
			$table->string('icon', 255);
			$table->mediumInteger('good_num')->comment('点赞');
			$table->mediumInteger('bad_num')->comment('差评');
			$table->string('password', 50)->comment('访问密码');
			$table->unsignedInteger('list_order');
			$table->unsignedInteger('hits');
			$table->string('status', 50)->default('post');
			$table->unsignedInteger('account_id');
			$table->unsignedTinyInteger('is_star')->comment('是否星标');
			$table->string('tag_note', 255)->comment('tag 标记');
			$table->dateTime('created_at')->nullable();
			$table->dateTime('updated_at')->nullable();
		});


	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('article_content');
	}
}
