<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSiteTagCategoryTable extends Migration
{
	/**
	 * Run the migrations.
	 * @return void
	 */
	public function up()
	{
		Schema::create('site_tag_category', function (Blueprint $table) {
			$table->integer('id');
			$table->string('name', 100)->default('')->comment('命名标识');
			$table->string('title', 255)->default('')->comment('标题');
			$table->integer('account_id')->default(0)->comment('账号ID');
			$table->dateTime('created_at')->nullable();
			$table->dateTime('updated_at')->nullable();

			$table->primary('id');
		});
	}

	/**
	 * Reverse the migrations.
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('site_tag_category');
	}
}
