<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSiteUrlTable extends Migration
{
	/**
	 * Run the migrations.
	 * @return void
	 */
	public function up()
	{
		Schema::create('site_url', function (Blueprint $table) {
			$table->increments('id');
			$table->string('title', 255)->default('');
			$table->string('description', 255)->default('');
			$table->string('icon', 255)->default('');
			$table->string('url', 255)->default('');
			$table->string('domain', 50)->default('');
			$table->integer('account_id')->default(0);
			$table->integer('list_order')->default(0);
			$table->integer('hits')->default(0);
			$table->tinyInteger('is_suggest')->default(0);
			$table->dateTime('created_at')->nullable();
			$table->dateTime('updated_at')->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('site_url');
	}
}
