<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateArticleBookTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('article_book', function(Blueprint $table) {
			$table->increments('id');
			$table->string('title', 255)->default('')->comment('书籍标题');
			$table->integer('account_id')->default(0)->comment('User Id');
			$table->integer('list_order')->default(0)->comment('显示排序');
			$table->tinyInteger('is_favor')->comment('是否喜欢');
			$table->integer('hits')->default(0)->comment('点击量');
			$table->dateTime('created_at')->nullable();
			$table->dateTime('updated_at')->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('article_book');
	}
}
