<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSiteUrlRelTagTable extends Migration
{
	/**
	 * Run the migrations.
	 * @return void
	 */
	public function up()
	{
		Schema::create('site_url_rel_tag', function (Blueprint $table) {
			$table->integer('url_id')->comment('url id');
			$table->integer('tag_id')->default(0)->comment('标签ID');
			$table->integer('user_url_id')->comment('用户URL ID');
			$table->integer('account_id')->default(0)->comment('用户ID');

		});
	}

	/**
	 * Reverse the migrations.
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('site_url_rel_tag');
	}
}
