<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSiteUserUrlTable extends Migration
{
	/**
	 * Run the migrations.
	 * @return void
	 */
	public function up()
	{
		Schema::create('site_user_url', function (Blueprint $table) {
			$table->increments('id');
			$table->integer('url_id')->default(0);
			$table->string('title', 255)->default('');
			$table->string('description', 255)->default('');
			$table->integer('account_id')->default(0);
			$table->tinyInteger('is_star')->nullable();
			$table->dateTime('created_at')->nullable();
			$table->dateTime('updated_at')->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('site_user_url');
	}
}
