<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserNoticeTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_notice', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('account_id')->comment('用户id');
            $table->string('type', 25)->comment('推送的类型');
            $table->string('image', 255)->comment('推送的图片');
            $table->string('link', 255)->comment('推送的链接');
            $table->string('content', 255)->comment('推送的文字内容');
            $table->string('active', 155)->comment('入口（跳转到H5或者功能点）');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            $table->unique('account_id', 'account_id_UNIQUE');
            $table->unique('id', 'id_UNIQUE');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_notice');
    }
}
