<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserProfileTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_profile', function (Blueprint $table) {
            $table->integer('id')->comment('账户id');
            $table->string('nickname', 45)->comment('昵称（备注）');
            $table->tinyInteger('sex')->comment('性别 0：男 1：女');
            $table->string('signature', 255)->comment('个性签名');
            $table->string('mobile', 45)->comment('手机号');
            $table->string('qq', 45)->comment('qq');
            $table->integer('area_id')->comment('地区id');
            $table->string('address', 45)->comment('地址');
            $table->string('head_pic', 100)->comment('头像');
            $table->decimal('money', 10, 2)->default(0.00)->comment('资金');
            $table->tinyInteger('is_chid_validated')->comment('实名认证的状态 0: 未认证, 1: 已经认证');
            $table->tinyInteger('lol_is_girl_validated')->comment('lol是否认证过女猎手');
            $table->tinyInteger('wz_is_girl_validated');
            $table->tinyInteger('pubg_is_girl_validated');
            $table->tinyInteger('lol_is_validated')->comment('lol是否认证过猎手');
            $table->tinyInteger('lol_validated_type')->comment('LOL认证猎手级别 0：普通1：优质 2：金牌');
            $table->tinyInteger('wz_is_validated');
            $table->tinyInteger('wz_validated_type');
            $table->tinyInteger('pubg_is_validated');
            $table->tinyInteger('pubg_validated_type');
            $table->string('truename', 45)->comment('真实姓名');
            $table->string('personal_pic', 100)->comment('个人形象主照片');
            $table->integer('punish_point')->comment('惩戒值/惩戒点数');
            $table->integer('punish_num')->comment('当天惩戒次数');
            $table->float('star', 8, 2)->default(0.00)->comment('对猎手的综合评分');
            $table->tinyInteger('order_listening')->comment('听单状态  0: No, 1:正在听单');
            $table->integer('friend_num')->comment('好友数量');
            $table->integer('fans_num')->comment('粉丝数量');
            $table->integer('follow_num')->comment('关注数量');
            $table->string('wz_game_nickname', 45)->comment('游戏昵称');
            $table->string('wz_game_system', 45)->comment('手机系统');
            $table->string('wz_game_login_way', 45)->comment('登录方式');
            $table->string('wz_good_at_position', 45)->comment('擅长位置');
            $table->string('wz_game_hero', 45)->comment('本命英雄');
            $table->string('lol_game_nickname', 45)->comment('游戏昵称');
            $table->string('lol_game_service', 45)->comment('游戏区服');
            $table->string('lol_good_at_position', 45)->comment('擅长位置');
            $table->string('lol_game_hero', 45)->comment('本命英雄');
            $table->string('pubg_game_nickname', 45)->comment('游戏昵称');
            $table->string('pubg_game_steamid', 45)->comment('Steam id');
            $table->string('pubg_game_rank', 45)->comment('赛季综合评分');

            $table->unique('id', 'id_UNIQUE');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_profile');
    }
}
