<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserPunishTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_punish', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('account_id')->comment('用户id');
            $table->unsignedTinyInteger('point')->comment('惩戒指数');
            $table->string('reason', 255)->comment('惩戒原因');
            $table->string('order_no', 255)->comment('订单号');
            $table->string('type', 45)->comment('惩戒类型（普通订单：hunter、女猎手:girl、车队订单:car）');
            $table->string('from', 45)->comment('惩戒类型');
            $table->dateTime('created_at')->nullable()->comment('创建时间↵');
            $table->dateTime('updated_at')->nullable()->comment('更新时间');

            $table->unique('account_id', 'account_id_UNIQUE');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_punish');
    }
}
