<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateFinanceCashTable extends Migration
{
	/**
	 * Run the migrations.
	 * @return void
	 */
	public function up()
	{
		Schema::create('finance_cash', function (Blueprint $table) {
			$table->increments('id')->comment('id');
			$table->string('cash_no', 255)->comment('流水号');
			$table->string('truename', 45)->comment('真实姓名');
			$table->integer('type')->comment('提现类型  0支付宝 1 微信 2银行卡');
			$table->integer('account_id');
			$table->string('bank_no', 45)->comment('提现账号');
			$table->decimal('amount', 10, 2)->default(0.00)->comment('金额');
			$table->integer('status')->comment('提现状态0：未处理 1：提现成功 2：提现失败');
			$table->decimal('fee', 10, 2)->default(0.00)->comment('手续费');
			$table->string('note', 255)->comment('备注');
			$table->integer('fail_editor_id')->comment('失败操作人');
			$table->dateTime('failed_at')->nullable()->comment('失败时间');
			$table->string('failed_reason', 255)->comment('失败原因');
			$table->string('flow_no', 45)->comment('失败流水号');
			$table->dateTime('success_at')->nullable()->comment('成功时间');
			$table->unsignedTinyInteger('is_transfer')->comment('是否自动提现');
			$table->dateTime('updated_at')->nullable()->comment('修改时间');
			$table->dateTime('created_at')->nullable()->comment('创建时间');
		});
	}

	/**
	 * Reverse the migrations.
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('finance_cash');
	}
}
