<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserListenTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_listen', function (Blueprint $table) {
            $table->unsignedInteger('account_id')->comment('猎手id');
            $table->unsignedTinyInteger('hunter_group')->default(1)->comment('猎手分类↵1:猎手2:优选3:金牌4:女猎手');
            $table->string('server_code', 45)->comment('大区代码');
            $table->string('dan', 45);

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_listen');
    }
}
