<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserValidateTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_validate', function (Blueprint $table) {
            $table->increments('id');
            $table->string('chid_no', 40)->comment('身份证号');
            $table->string('chid_pic_y', 100)->comment('身份证正面');
            $table->string('chid_pic_n', 100)->comment('身份证反面');
            $table->string('chid_validate_status', 20)->comment('个人信息是否认证 (wait, success, fail)');
            $table->dateTime('chid_validate_at')->nullable()->comment('个人信息认证时间↵');
            $table->unsignedInteger('chid_editor_id')->comment('操作人↵');
            $table->string('chid_failed_reason', 255)->comment('失败原因↵');
            $table->dateTime('chid_failed_at')->nullable()->comment('失败时间↵');
            $table->unsignedInteger('lol_validate_sex_type')->comment('类型 0：猎手:1：女猎手↵');
            $table->string('lol_girl_validate_video', 255)->comment('↵↵视频↵');
            $table->string('lol_girl_validate_pic1', 255)->comment('照片1↵');
            $table->string('lol_girl_validate_pic2', 255)->comment('照片2↵');
            $table->string('lol_girl_validate_pic3', 255)->comment('照片3↵');
            $table->string('lol_girl_validate_status', 45)->comment('女猎手认证状态 wait,success,fail↵');
            $table->dateTime('lol_girl_validate_at')->nullable()->comment('女猎手认证时间↵');
            $table->string('lol_girl_validate_failed_reason', 255)->comment('女猎手认证失败原因↵');
            $table->unsignedInteger('lol_validate_type')->comment('lol认证类型 0：普通 1：优质 2：金牌猎手↵');
            $table->string('lol_validate_status', 45)->comment('none, wait,success,fail↵');
            $table->dateTime('lol_validate_at')->nullable()->comment('认证时间↵');
            $table->string('lol_validate_failed_reason', 255);
            $table->string('lol_game_server', 50)->comment('游戏大区↵');
            $table->string('lol_game_role', 100)->comment('游戏角色↵');
            $table->string('lol_game_ability', 45)->comment('lol游戏资质段位↵');
            $table->string('lol_game_user_pic', 100)->comment('lol个人形象照↵');
            $table->string('lol_game_pic', 100)->comment('lol游戏封面照↵');
            $table->string('lol_game_status', 50)->comment('wait,success,fail↵');
            $table->dateTime('lol_game_fail_at')->nullable()->comment('认证失败时间');
            $table->string('lol_game_failed_reason', 255)->comment('游戏资质认证失败原因↵');
            $table->string('lol_recheck_image', 100)->comment('复审资料↵');
            $table->string('lol_recheck_status', 50)->comment('none,wait,success, fail↵');
            $table->dateTime('lol_recheck_success_at')->nullable()->comment('复审成功的时间↵');
            $table->dateTime('lol_recheck_failed_at')->nullable()->comment('复审失败时间↵');
            $table->string('lol_recheck_failed_reason', 255)->comment('复审失败的原因↵');
            $table->string('lol_rule_status', 45)->comment('none,fail,success↵');
            $table->dateTime('lol_rule_success_at')->nullable()->comment('规则考核成功时间↵');
            $table->dateTime('lol_rule_fail_at')->nullable()->comment('规则考核失败时间↵');
            $table->unsignedInteger('wz_validate_sex_type')->comment('类型 0：猎手:1：女猎手↵');
            $table->string('wz_girl_validate_video', 155)->comment('视频↵');
            $table->string('wz_girl_validate_pic1', 155)->comment('照片1↵');
            $table->string('wz_girl_validate_pic2', 155)->comment('照片2↵');
            $table->string('wz_girl_validate_pic3', 155)->comment('照片3↵');
            $table->string('wz_girl_validate_status', 45)->comment('女猎手认证状态 wait,success,fail↵');
            $table->dateTime('wz_girl_validate_at')->nullable()->comment('女猎手认证时间↵');
            $table->string('wz_girl_validate_failed_reason', 255)->comment('女猎手认证失败原因↵');
            $table->string('wz_validate_type', 45)->comment('wz认证类型 0：普通 1：优质 2：金牌猎手↵');
            $table->string('wz_validate_status', 45)->comment('none, wait,success,fail↵');
            $table->dateTime('wz_validate_at')->nullable()->comment('认证时间↵');
            $table->string('wz_validate_failed_reason', 255)->comment('wz认证失败原因↵');
            $table->string('wz_game_server', 100)->comment('游戏大区↵');
            $table->string('wz_game_role', 45)->comment('游戏角色↵');
            $table->string('wz_game_ability', 45)->comment('wz游戏资质段位↵');
            $table->string('wz_game_user_pic', 155)->comment('wz个人形象照↵');
            $table->string('wz_game_pic', 155)->comment('wz游戏封面照↵');
            $table->string('wz_game_status', 45)->comment('wait,success,fail↵');
            $table->dateTime('wz_game_failed_at')->nullable()->comment('游戏资质认证失败时间↵');
            $table->string('wz_game_failed_reason', 255)->comment('游戏资质认证失败原因↵');
            $table->string('wz_recheck_image', 155)->comment('复审资料↵');
            $table->string('wz_recheck_status', 45)->comment('none,wait,success, fail↵');
            $table->dateTime('wz_recheck_success_at')->nullable()->comment('复审成功的时间↵');
            $table->dateTime('wz_recheck_failed_at')->nullable()->comment('复审失败时间↵');
            $table->string('wz_recheck_failed_reason', 255)->comment('复审失败的原因↵');
            $table->string('wz_rule_status', 45)->comment('none,fail,success↵');
            $table->dateTime('wz_rule_success_at')->nullable()->comment('规则考核成功时间↵');
            $table->string('wz_rule_fail_at', 45)->comment('规则考核失败时间↵');
            $table->string('pubg_validate_sex_type', 45)->comment('类型 0：猎手:1：女猎手↵');
            $table->string('pubg_girl_validate_video', 155)->comment('视频↵');
            $table->string('pubg_girl_validate_pic1', 155)->comment('照片1↵');
            $table->string('pubg_girl_validate_pic2', 155)->comment('照片2↵');
            $table->string('pubg_girl_validate_pic3', 155)->comment('照片3↵');
            $table->string('pubg_girl_validate_status', 45)->comment('女猎手认证状态↵');
            $table->dateTime('pubg_girl_validate_at')->nullable()->comment('女猎手认证时间↵');
            $table->string('pubg_girl_validate_failed_reason', 255)->comment('女猎手认证失败原因↵');
            $table->string('pubg_validate_type', 45)->comment('认证类型 0：普通 1：优质 2：金牌猎手↵');
            $table->dateTime('pubg_validate_at')->nullable()->comment('认证时间↵');
            $table->string('pubg_validate_status', 45)->default('none')->comment('none, wait,success,fail↵');
            $table->string('pubg_validate_failed_reason', 255)->comment('认证失败原因↵');
            $table->string('pubg_game_server', 155)->comment('游戏大区↵');
            $table->string('pubg_game_role', 45)->comment('游戏角色↵');
            $table->string('pubg_game_ability', 45)->comment('游戏资质段位↵');
            $table->string('pubg_game_user_pic', 155)->comment('个人形象照↵');
            $table->string('pubg_game_pic', 155)->comment('游戏封面照↵');
            $table->string('pubg_game_status', 45)->comment('wait,success,fail↵');
            $table->dateTime('pubg_game_fail_at')->nullable()->comment('游戏资质认证失败时间↵');
            $table->string('pubg_game_fail_reason', 255)->comment('游戏资质认证失败原因↵');
            $table->string('pubg_recheck_image', 155)->comment('复审资料↵');
            $table->dateTime('pubg_recheck_success_at')->nullable()->comment('复审成功的时间↵');
            $table->dateTime('pubg_recheck_fail_at')->nullable()->comment('复审失败时间↵');
            $table->string('pubg_recheck_failed_reason', 255)->comment('复审失败的原因↵');
            $table->string('pubg_recheck_status', 45)->comment('none,wait,success, fail↵');
            $table->string('pubg_rule_status', 45)->comment('none,fail,success↵');
            $table->dateTime('pubg_rule_success_at')->nullable()->comment('规则考核成功时间↵');
            $table->dateTime('pubg_rule_fail_at')->nullable()->comment('规则考核失败时间↵');
            $table->string('binding_status', 45)->comment('绑定状态 1已绑定 0未绑定↵');
            $table->unsignedInteger('binding_pay_type')->comment('绑定类型 0:支付宝 1：微信 2：银行卡↵');
            $table->string('binding_pay_no', 105)->comment('绑定支付宝/微信/银行卡号↵');
            $table->unsignedInteger('lol_bond_status')->comment('lol保证金状态 0 未提交 1：已提交↵');
            $table->string('lol_bond_flow_no', 50)->comment('lol保证金流水号↵');
            $table->string('lol_bond_desc', 100)->comment('lol保证金描述↵');
            $table->dateTime('lol_bond_at')->nullable()->comment('lol保证金提交时间↵');
            $table->unsignedInteger('wz_bond_status')->nullable()->comment('wz保证金状态↵');
            $table->string('wz_bond_flow_no', 100)->comment('wz保证金流水号↵');
            $table->string('wz_bond_desc', 100)->comment('wz保证金描述↵');
            $table->dateTime('wz_bond_at')->nullable()->comment('wz保证金提交时间↵');
            $table->unsignedInteger('pubg_bond_status')->comment('pubg保证金状态↵');
            $table->string('pubg_bond_flow_no', 100)->comment('pubg保证金流水号↵');
            $table->string('pubg_bond_desc', 255)->comment('pubg保证金描述↵');
            $table->dateTime('pubg_bond_at')->nullable()->comment('pubg保证金提交时间↵');
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_validate');
    }
}
