<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateFinanceChargeTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('finance_charge', function (Blueprint $table) {
            $table->increments('id');
            $table->string('charge_no', 50)->comment('充值流水号');
            $table->string('truename', 50)->comment('真实姓名');
            $table->integer('type')->comment('充值类型 0支付宝 1微信');
            $table->integer('account_id')->comment('充值账号');
            $table->decimal('amount', 10, 2)->default(0.00)->comment('金额');
            $table->tinyInteger('status')->comment('充值状态 0：未处理 1：充值成功 2：充值失败');
            $table->decimal('fee', 10, 2)->default(0.00)->comment('手续费');
            $table->string('note', 255)->comment('备注');
            $table->integer('fail_editor_id')->comment('失败操作人');
            $table->dateTime('failed_at')->nullable()->comment('失败时间');
            $table->string('failed_reason', 255)->comment('失败原因');
            $table->string('flow_no', 45)->comment('失败流水号');
            $table->dateTime('success_at')->nullable()->comment('成功时间');
            $table->dateTime('updated_at')->nullable()->comment('修改时间');
            $table->dateTime('created_at')->nullable()->comment('创建时间');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('finance_charge');
    }
}
