<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserProfileTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_profile', function (Blueprint $table) {
            $table->integer('account_id')->unsigned()->default(0)->comment('账户id');
            $table->string('nickname', 45)->default('')->comment('昵称（备注）');
            $table->string('sex',10)->default('')->comment('性别 男:man 女：female');
            $table->string('signature', 255)->default('')->comment('个性签名');
            $table->string('mobile', 45)->default('')->comment('手机号');
            $table->string('qq', 45)->default('')->comment('qq');
            $table->integer('area_id')->unsigned()->default(0)->comment('地区id');
            $table->string('address', 45)->default('')->comment('地址');
            $table->string('head_pic', 100)->default('')->comment('头像');
            $table->decimal('money', 10, 2)->unsigned()->default(0.00)->comment('资金');
            $table->tinyInteger('is_chid_validated')->unsigned()->default(0)->comment('实名认证的状态 0: 未认证, 1: 已经认证');
            $table->tinyInteger('lol_is_girl_validated')->unsigned()->default(0)->comment('lol是否认证过女猎手');
            $table->tinyInteger('wz_is_girl_validated')->unsigned()->default(0)->comment('wz是否认证过女猎手');
            $table->tinyInteger('pubg_is_girl_validated')->unsigned()->default(0)->comment('pubg是否认证过女猎手');
            $table->tinyInteger('lol_is_validated')->unsigned()->default(0)->comment('lol是否认证过猎手');
            $table->string('lol_validated_type',10)->default('')->comment('lol认证猎手级别:normal:普通猎手,good:优选猎手,gold:金牌猎手');
            $table->tinyInteger('wz_is_validated')->unsigned()->default(0)->comment('wz是否认证过猎手');
            $table->string('wz_validated_type',10)->default('')->comment('wz认证猎手级别:normal:普通猎手,good:优选猎手,gold:金牌猎手');
            $table->tinyInteger('pubg_is_validated')->unsigned()->default(0)->comment('pubg是否认证过猎手');
            $table->string('pubg_validated_type',10)->default('')->comment('pubg认证猎手级别:normal:普通猎手,good:优选猎手,gold:金牌猎手');
            $table->string('truename', 45)->default('')->comment('真实姓名');
            $table->string('personal_pic', 100)->default('')->comment('个人形象主照片');
            $table->integer('punish_point')->unsigned()->default(0)->comment('惩戒值/惩戒点数');
            $table->integer('punish_num')->unsigned()->default(0)->comment('当天惩戒次数');
            $table->float('star', 8, 2)->unsigned()->default(0.00)->comment('对猎手的综合评分');
            $table->tinyInteger('order_listening')->unsigned()->default(0)->comment('听单状态  0: No, 1:正在听单');
            $table->integer('friend_num')->unsigned()->default(0)->comment('好友数量');
            $table->integer('fans_num')->unsigned()->default(0)->comment('粉丝数量');
            $table->integer('follow_num')->unsigned()->default(0)->comment('关注数量');
            $table->string('wz_game_nickname', 45)->default('')->comment('游戏昵称');
            $table->string('wz_game_system', 45)->default('')->comment('手机系统');
            $table->string('wz_game_login_way', 45)->default('')->comment('登录方式');
            $table->string('wz_good_at_position', 45)->default('')->comment('擅长位置');
            $table->string('wz_game_hero', 45)->default('')->comment('本命英雄');
            $table->string('lol_game_nickname', 45)->default('')->comment('游戏昵称');
            $table->string('lol_game_service', 45)->default('')->comment('游戏区服');
            $table->string('lol_good_at_position', 45)->default('')->comment('擅长位置');
            $table->string('lol_game_hero', 45)->default('')->comment('本命英雄');
            $table->string('pubg_game_nickname', 45)->default('')->comment('游戏昵称');
            $table->string('pubg_game_steamid', 45)->default('')->comment('Steam id');
            $table->string('pubg_game_rank', 45)->default('')->comment('赛季综合评分');

            $table->unique('account_id', 'id_UNIQUE');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_profile');
    }
}
