<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSysAreaTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sys_area', function (Blueprint $table) {
            $table->increments('id');
            $table->string('code', 45)->comment('编码');
            $table->string('title', 50)->comment('地区名称');
            $table->integer('parent_id')->comment('父级ID');
            $table->tinyInteger('top_parent_id')->comment('顶层ID, 父元素');
            $table->text('children')->comment('所有的子元素');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sys_area');
    }
}
