<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSysCategoryTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sys_category', function (Blueprint $table) {
            $table->increments('id');
            $table->string('type', 20)->default('help')->comment('类型    activiy:活动 help：帮助');
            $table->unsignedTinyInteger('parent_id')->comment('父id');
            $table->string('title', 45);
            $table->string('updated_at', 45)->nullable()->comment('修改时间');
            $table->string('created_at', 45)->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sys_category');
    }
}
