<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreatePamBindTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('pam_bind', function (Blueprint $table) {
            $table->unsignedInteger('account_id');
            $table->string('qq_key', 255)->comment('qq绑定id');
            $table->string('qq_union_id', 255)->comment('qq union id');
            $table->string('wx_union_id', 255)->comment('微信union');
            $table->string('wx_key', 255)->comment('微信绑定id');
            $table->dateTime('updated_at')->nullable();
            $table->dateTime('created_at')->nullable();

            $table->unique('account_id', 'account_id_UNIQUE');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('pam_bind');
    }
}
